PROGRAM_NAME='Eiki-LC-XT4-include'

DEFINE_CONSTANT

VOLATILE CHAR PROJ_ON[] = '00'
VOLATILE CHAR PROJ_OFF[] = '01'

VOLATILE CHAR PROJ_MUTE_ON[] = '0D'
VOLATILE CHAR PROJ_MUTE_OFF[] = '0E'

VOLATILE CHAR PROJ_AUTOADJUST[] = '89'

VOLATILE CHAR PROJ_INPUT_1[] = '05'
VOLATILE CHAR PROJ_INPUT_2[] = '06'
VOLATILE CHAR PROJ_INPUT_3[] = '07'
VOLATILE CHAR PROJ_INPUT_4[] = '08'
